name: Perform tests

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'test*'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew zoomable:testDebugUnitTest

  instrument_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew zoomable:connectedDebugAndroidTest
          api: 25
          tag: default
          abi: x86