name: Perform tests

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'test*'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew zoomable:testDebugUnitTest

  gmd_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew zoomable:allDevicesDebugAndroidTest --info --stacktrace
